import { relations, sql } from 'drizzle-orm'
import {
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core'
import { user } from './identity'

/**
 * The Literature Tracker's own tables — the first user-owned data on this site.
 *
 * Written to the letter of research/data-modeling/article-core-schema.md and
 * research/data-modeling/upload-jobs-schema.md, under the cross-cutting
 * conventions in research/data-modeling/zero-schema-conventions.md
 * (`timestamptz` timestamps, hard deletes, `ON DELETE CASCADE` on ownership
 * FKs, UUIDv7 primary keys).
 *
 * One deviation from those documents, forced by the identity schema that
 * already exists: they specify `user_id uuid`, but Better Auth generates
 * `user.id` as `text` (see identity.ts), and Postgres cannot point a `uuid`
 * foreign key at a `text` primary key. The ownership columns are therefore
 * `text`. Each table's own primary key is still `uuid`, as decided.
 */

/**
 * One author of a paper.
 *
 * `name` is always populated — it is what every display surface renders.
 * `given`/`family` are filled in only when GROBID's TEI output carries
 * structured `persName` data, so consumers must treat them as optional.
 */
export interface Author {
  name: string
  given?: string
  family?: string
}

/** Where the reader has got to. Mutually exclusive by construction. */
export type ArticleStatus = 'pending' | 'reading' | 'read'

/**
 * How much metadata the pipeline managed to attach.
 *
 * `grobid_only` is a success: Semantic Scholar enrichment is non-fatal, so an
 * article whose enrichment failed is still a complete article. `failed` means
 * GROBID could not extract required fields and the row needs a human — see
 * upload-jobs-schema.md.
 */
export type ArticleExtractionStatus =
  | 'pending'
  | 'grobid_only'
  | 'enriched'
  | 'failed'

export const articles = pgTable(
  'articles',
  {
    /** Client-generated UUIDv7, or — for an upload — the job's pre-allocated id. */
    id: uuid('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),

    title: text('title').notNull(),
    authors: jsonb('authors').$type<Author[]>().notNull(),
    /**
     * Every author's name, lowercased, maintained by Postgres rather than by
     * application code. Exists to make a future server-side author search
     * indexable; the reactive client-side search does not read it.
     *
     * `generated ... stored` columns only replicate to Zero on Postgres 18+,
     * which is why the project's version floor is 18 (article-core-schema.md).
     */
    authorsSearch: text('authors_search').generatedAlwaysAs(
      sql`lower(jsonb_path_query_array(authors, '$[*].name')::text)`,
    ),
    publicationYear: integer('publication_year'),
    venue: text('venue'),
    doi: text('doi'),
    abstract: text('abstract'),
    notes: text('notes'),

    /** Garage object key, `lit-tracker/{user_id}/{article_id}/source.pdf`. */
    pdfObjectKey: text('pdf_object_key').notNull(),
    /** Semantic Scholar's `paperId`, set only on successful enrichment. */
    semanticScholarId: text('semantic_scholar_id'),

    status: text('status').$type<ArticleStatus>().notNull().default('pending'),
    extractionStatus: text('extraction_status')
      .$type<ArticleExtractionStatus>()
      .notNull()
      .default('pending'),

    createdAt: timestamp('created_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [
    // Trigram GIN, not full-text: `ILIKE '%partial%'` over proper names is what
    // author search needs, and stemming/tokenizing would be the wrong shape.
    index('articles_authors_search_trgm_idx').using(
      'gin',
      sql`${table.authorsSearch} gin_trgm_ops`,
    ),
    // Every query for this table filters by owner, the same reason the identity
    // tables index their own `user_id`.
    index('articles_user_id_idx').on(table.userId),
  ],
)

/** Whether an upload still needs attention. Resolved jobs are deleted, not marked. */
export type UploadJobStatus = 'processing' | 'failed'

export const uploadJobs = pgTable(
  'upload_jobs',
  {
    /**
     * Server-generated by Postgres 18's native `uuidv7()` — the one table whose
     * rows are never a client-side optimistic create, so the client-generated-id
     * rationale does not apply (zero-schema-conventions.md names this exception).
     *
     * This value is also the **pre-allocated id of the future article**: the PDF
     * is written to blob storage under it before the `articles` row exists, so
     * no blob is ever copied or moved once extraction inserts that row.
     */
    id: uuid('id').primaryKey().default(sql`uuidv7()`),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),

    /** The name the user uploaded, shown verbatim in the job-list popup. */
    filename: text('filename').notNull(),

    status: text('status')
      .$type<UploadJobStatus>()
      .notNull()
      .default('processing'),
    /** Populated only when `status` is `failed`; the reason shown to the user. */
    failureReason: text('failure_reason'),

    /**
     * Null only in the window before the extract stage inserts the article;
     * always equal to `id` once set. A real FK rather than a bare shared id, so
     * deleting the article cleans the job up automatically.
     */
    articleId: uuid('article_id').references(() => articles.id, {
      onDelete: 'cascade',
    }),

    pdfObjectKey: text('pdf_object_key').notNull(),

    createdAt: timestamp('created_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index('upload_jobs_user_id_idx').on(table.userId)],
)

export const articlesRelations = relations(articles, ({ one, many }) => ({
  owner: one(user, {
    fields: [articles.userId],
    references: [user.id],
  }),
  uploadJobs: many(uploadJobs),
}))

export const uploadJobsRelations = relations(uploadJobs, ({ one }) => ({
  owner: one(user, {
    fields: [uploadJobs.userId],
    references: [user.id],
  }),
  article: one(articles, {
    fields: [uploadJobs.articleId],
    references: [articles.id],
  }),
}))
