import { relations, sql } from 'drizzle-orm'
import {
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
} from 'drizzle-orm/pg-core'
import type { ArticleStatus } from '~/lit-tracker/article-status'
import { user } from './identity'

/**
 * The Literature Tracker's own tables — the first user-owned data on this site.
 *
 * Written to the letter of research/data-modeling/article-core-schema.md and
 * research/data-modeling/upload-jobs-schema.md, under the cross-cutting
 * conventions in research/data-modeling/zero-schema-conventions.md
 * (`timestamptz` timestamps, hard deletes, `ON DELETE CASCADE` on ownership
 * FKs, UUIDv7 primary keys).
 *
 * One deviation from those documents, forced by the identity schema that
 * already exists: they specify `user_id uuid`, but Better Auth generates
 * `user.id` as `text` (see identity.ts), and Postgres cannot point a `uuid`
 * foreign key at a `text` primary key. The ownership columns are therefore
 * `text`. Each table's own primary key is still `uuid`, as decided.
 */

/**
 * One author of a paper.
 *
 * `name` is always populated — it is what every display surface renders.
 * `given`/`family` are filled in only when GROBID's TEI output carries
 * structured `persName` data, so consumers must treat them as optional.
 */
export interface Author {
  name: string
  given?: string
  family?: string
}

/**
 * Where the reader has got to. Defined away from this file — see
 * `src/lit-tracker/article-status.ts` for why — and re-exported here so the
 * schema still reads as the description of its own columns.
 */
export { ARTICLE_STATUSES } from '~/lit-tracker/article-status'
export type { ArticleStatus }

/**
 * How much metadata the pipeline managed to attach.
 *
 * `grobid_only` is a success: Semantic Scholar enrichment is non-fatal, so an
 * article whose enrichment failed is still a complete article. `failed` means
 * GROBID could not extract required fields and the row needs a human — see
 * upload-jobs-schema.md.
 */
export type ArticleExtractionStatus =
  | 'pending'
  | 'grobid_only'
  | 'enriched'
  | 'failed'

export const articles = pgTable(
  'articles',
  {
    /** Client-generated UUIDv7, or — for an upload — the job's pre-allocated id. */
    id: uuid('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),

    title: text('title').notNull(),
    authors: jsonb('authors').$type<Author[]>().notNull(),
    /**
     * Every author's name, lowercased, maintained by Postgres rather than by
     * application code. Exists to make a future server-side author search
     * indexable; the reactive client-side search does not read it.
     *
     * `generated ... stored` columns only replicate to Zero on Postgres 18+,
     * which is why the project's version floor is 18 (article-core-schema.md).
     */
    authorsSearch: text('authors_search').generatedAlwaysAs(
      sql`lower(jsonb_path_query_array(authors, '$[*].name')::text)`,
    ),
    publicationYear: integer('publication_year'),
    venue: text('venue'),
    doi: text('doi'),
    abstract: text('abstract'),
    notes: text('notes'),

    /** Garage object key, `lit-tracker/{user_id}/{article_id}/source.pdf`. */
    pdfObjectKey: text('pdf_object_key').notNull(),
    /** Semantic Scholar's `paperId`, set only on successful enrichment. */
    semanticScholarId: text('semantic_scholar_id'),

    status: text('status').$type<ArticleStatus>().notNull().default('pending'),
    extractionStatus: text('extraction_status')
      .$type<ArticleExtractionStatus>()
      .notNull()
      .default('pending'),

    createdAt: timestamp('created_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [
    // Trigram GIN, not full-text: `ILIKE '%partial%'` over proper names is what
    // author search needs, and stemming/tokenizing would be the wrong shape.
    index('articles_authors_search_trgm_idx').using(
      'gin',
      sql`${table.authorsSearch} gin_trgm_ops`,
    ),
    // Every query for this table filters by owner, the same reason the identity
    // tables index their own `user_id`.
    index('articles_user_id_idx').on(table.userId),
  ],
)

/** Whether an upload still needs attention. Resolved jobs are deleted, not marked. */
export type UploadJobStatus = 'processing' | 'failed'

export const uploadJobs = pgTable(
  'upload_jobs',
  {
    /**
     * Server-generated by Postgres 18's native `uuidv7()` — the one table whose
     * rows are never a client-side optimistic create, so the client-generated-id
     * rationale does not apply (zero-schema-conventions.md names this exception).
     *
     * This value is also the **pre-allocated id of the future article**: the PDF
     * is written to blob storage under it before the `articles` row exists, so
     * no blob is ever copied or moved once extraction inserts that row.
     */
    id: uuid('id').primaryKey().default(sql`uuidv7()`),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),

    /** The name the user uploaded, shown verbatim in the job-list popup. */
    filename: text('filename').notNull(),

    status: text('status')
      .$type<UploadJobStatus>()
      .notNull()
      .default('processing'),
    /** Populated only when `status` is `failed`; the reason shown to the user. */
    failureReason: text('failure_reason'),

    /**
     * Null only in the window before the extract stage inserts the article;
     * always equal to `id` once set. A real FK rather than a bare shared id, so
     * deleting the article cleans the job up automatically.
     */
    articleId: uuid('article_id').references(() => articles.id, {
      onDelete: 'cascade',
    }),

    pdfObjectKey: text('pdf_object_key').notNull(),

    createdAt: timestamp('created_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index('upload_jobs_user_id_idx').on(table.userId)],
)

/**
 * A label the user made up, applied to any number of their own articles.
 *
 * Written to the letter of research/data-modeling/tags-and-reading-status.md.
 * The thing most worth knowing about this table is what is *not* in it:
 * **reading status is not a tag.** `pending`/`reading`/`read` are values of
 * `articles.status`, and the collection view synthesizes three chips that render
 * identically to real tags. There are no seeded rows here, no `kind` column, and
 * no trigger protecting built-ins — mutual exclusivity comes free from a
 * single-valued column instead of from a partial unique index. The schema doc
 * records the rejected alternative and why.
 *
 * Tags are per-user. There is no shared or cross-user tag anywhere in the
 * specs, which is why `user_id` is on this table and not inferred through the
 * articles a tag happens to be applied to: a tag exists whether or not anything
 * currently carries it.
 */
export const tags = pgTable(
  'tags',
  {
    /**
     * Client-generated UUIDv7. These are the first rows on the site created
     * from the browser rather than by a job handler, so this convention finally
     * has a real consumer (zero-schema-conventions.md).
     */
    id: uuid('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),

    /** As the user typed it. Shown verbatim on the card and in the filter rail. */
    name: text('name').notNull(),

    createdAt: timestamp('created_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  // No `updated_at`: nothing updates a tag. The decided model has create and
  // delete only — renaming is not specified anywhere, so it is not offered.
  (table) => [index('tags_user_id_idx').on(table.userId)],
)

/**
 * One tag applied to one article.
 *
 * Plain many-to-many join, with the `unique (article_id, tag_id)` the schema doc
 * specifies. That constraint is what makes "apply a tag" idempotent at the
 * database rather than in a check the client could race — which matters more
 * here than usual, because Zero rebases an optimistic mutation repeatedly as
 * authoritative changes arrive, so the same attach genuinely does run more than
 * once.
 *
 * No `user_id` of its own, unlike every other table here. Both ends already
 * belong to exactly one user and cascade from them, so a third copy of the owner
 * would be a denormalization with nothing to gain and a way to disagree.
 * Authorization still checks ownership — it reads it through the article and the
 * tag, which is the only place it is true.
 */
export const articleTags = pgTable(
  'article_tags',
  {
    /** Client-generated UUIDv7, as above. */
    id: uuid('id').primaryKey(),
    articleId: uuid('article_id')
      .notNull()
      .references(() => articles.id, { onDelete: 'cascade' }),
    tagId: uuid('tag_id')
      .notNull()
      .references(() => tags.id, { onDelete: 'cascade' }),

    createdAt: timestamp('created_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    unique('article_tags_article_id_tag_id_key').on(
      table.articleId,
      table.tagId,
    ),
    // The unique constraint above already indexes `(article_id, tag_id)`, which
    // serves every lookup starting from an article. This is the other
    // direction — "which articles carry this tag", and the scan Postgres does
    // to cascade a tag deletion, neither of which a leading-column index helps.
    // Postgres does not index a foreign key on its own.
    index('article_tags_tag_id_idx').on(table.tagId),
  ],
)

/**
 * One bibliography entry parsed from a citing article's PDF — the citation
 * graph, stored as edges.
 *
 * Written to the letter of research/data-modeling/citation-graph-schema.md.
 * Two things about it are easy to misread:
 *
 * - **A placeholder is not a separate entity.** Every parsed reference becomes
 *   a row immediately, whether or not the paper it names is in the collection.
 *   `cited_article_id IS NULL` *is* "not in collection", and "graduation" is
 *   nothing more than filling that column in later. The denormalized
 *   `title`/`authors`/`publication_year` are what let such a row render with no
 *   join at all.
 * - **The table is its own inverse.** "References of A" and "articles citing A"
 *   are the same rows read from opposite ends, which is why there is no
 *   second, separately-maintained index of the reverse direction.
 *
 * `citation_edges` rather than `references` because `REFERENCES` is a reserved
 * SQL key word, and quoting it in every hand-written query and every generated
 * artifact would be pure friction.
 */
export const citationEdges = pgTable(
  'citation_edges',
  {
    /** Client-generated UUIDv7, per zero-schema-conventions.md. */
    id: uuid('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),

    /** The article whose bibliography this entry came out of. */
    citingArticleId: uuid('citing_article_id')
      .notNull()
      .references(() => articles.id, { onDelete: 'cascade' }),
    /**
     * The referenced paper, once it turns out to also be in this user's
     * collection. Null until then — and null again if that article is deleted:
     * the citing paper still cited it, so `set null` reverts this row to a
     * placeholder rather than erasing a bibliography entry that really exists.
     */
    citedArticleId: uuid('cited_article_id').references(() => articles.id, {
      onDelete: 'set null',
    }),

    /** As the citing paper printed it — the display fields for an unresolved row. */
    title: text('title').notNull(),
    authors: jsonb('authors').$type<Author[]>().notNull(),
    publicationYear: integer('publication_year'),
    /** The referenced paper's Semantic Scholar `paperId`, when enrichment found one. */
    semanticScholarId: text('semantic_scholar_id'),

    createdAt: timestamp('created_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [
    // Data integrity, not an upsert mechanism: one article cannot cite the same
    // resolved paper twice. Re-extraction deletes and reinserts instead.
    unique('citation_edges_citing_s2_key').on(
      table.citingArticleId,
      table.semanticScholarId,
    ),
    index('citation_edges_citing_idx').on(table.citingArticleId),
    index('citation_edges_cited_idx').on(table.citedArticleId),
    // Partial, because the only query that reads it is graduation: "which of
    // this user's unresolved edges does the article just uploaded satisfy?"
    // Resolved rows are dead weight in that index.
    index('citation_edges_user_s2_idx')
      .on(table.userId, table.semanticScholarId)
      .where(sql`${table.citedArticleId} is null`),
  ],
)

export const articlesRelations = relations(articles, ({ one, many }) => ({
  owner: one(user, {
    fields: [articles.userId],
    references: [user.id],
  }),
  uploadJobs: many(uploadJobs),
  /** The join rows, not the tags — `article_tags` is a table in its own right. */
  articleTags: many(articleTags),
  /** This article's own bibliography. */
  references: many(citationEdges, { relationName: 'citingArticle' }),
  /** The bibliography entries of other articles that point at this one. */
  citedBy: many(citationEdges, { relationName: 'citedArticle' }),
}))

/**
 * Both ends are named explicitly because `citation_edges` points at `articles`
 * twice — without `relationName` Drizzle cannot tell which foreign key each
 * side of the graph is travelling along.
 */
export const citationEdgesRelations = relations(citationEdges, ({ one }) => ({
  owner: one(user, {
    fields: [citationEdges.userId],
    references: [user.id],
  }),
  citingArticle: one(articles, {
    fields: [citationEdges.citingArticleId],
    references: [articles.id],
    relationName: 'citingArticle',
  }),
  citedArticle: one(articles, {
    fields: [citationEdges.citedArticleId],
    references: [articles.id],
    relationName: 'citedArticle',
  }),
}))

export const tagsRelations = relations(tags, ({ one, many }) => ({
  owner: one(user, {
    fields: [tags.userId],
    references: [user.id],
  }),
  articleTags: many(articleTags),
}))

export const articleTagsRelations = relations(articleTags, ({ one }) => ({
  article: one(articles, {
    fields: [articleTags.articleId],
    references: [articles.id],
  }),
  tag: one(tags, {
    fields: [articleTags.tagId],
    references: [tags.id],
  }),
}))

export const uploadJobsRelations = relations(uploadJobs, ({ one }) => ({
  owner: one(user, {
    fields: [uploadJobs.userId],
    references: [user.id],
  }),
  article: one(articles, {
    fields: [uploadJobs.articleId],
    references: [articles.id],
  }),
}))
