import type { Transaction } from '@rocicorp/zero'
import { defineMutator, defineMutators } from '@rocicorp/zero'
import { z } from 'zod'
// From the domain module, not from `db/schema` which re-exports it: this file
// runs in the browser too, and the schema module pulls in Drizzle's Postgres
// dialect.
import { ANNOTATION_TYPES } from '~/lit-tracker/annotation-type'
import { ARTICLE_STATUSES } from '~/lit-tracker/article-status'
import {
  requireOwnedAnnotation,
  requireOwnedArticle,
  requireOwnedTag,
  requireSession,
} from './ownership'
import { zql } from './schema.gen'

// Re-exported so callers handling a refusal — the toast, and this module's
// tests — can name the thing they are handling without reaching past it.
export { MutationRefusedError } from './ownership'

/**
 * Every write the client may ask Zero to perform, and — because Zero has no
 * permissions layer behind this file — every write-authorization decision on the
 * site's user-owned data. `queries.ts` is the mirror image of this for reads.
 *
 * Three properties hold across all six, and each is a rule rather than a
 * coincidence:
 *
 * - **The owner comes from `ctx`, never from arguments.** `ctx` is derived
 *   server-side from the validated session (`context.ts`); arguments arrive
 *   verbatim from the browser. A mutator taking a `userId` argument would let
 *   any signed-in client write into any other account, and nothing further down
 *   would catch it.
 * - **Every id argument is checked before it is written to**, via `ownership.ts`.
 *   Zero's CRUD addresses rows by primary key alone, so an unchecked id is
 *   someone else's row.
 * - **Each one is safe to run more than once.** Zero re-runs a pending mutation
 *   on the client whenever it rebases onto newly-arrived authoritative data, so
 *   a mutator that only works the first time produces a UI that flickers or
 *   throws for no reason the user did anything to cause.
 *
 * A copy of each of these runs on the client, against its local data, to apply
 * the write optimistically. That copy is a convenience, not a control: it will
 * cheerfully apply a write the server then refuses, which is why the refusal has
 * somewhere to go (`useArticleMutations` raises a toast) and why the
 * authoritative answer is the one this file computes at `/api/zero/mutate`.
 */
export const mutators = defineMutators({
  tags: {
    /**
     * Create a tag.
     *
     * The id is generated by the client — these are the first rows on this site
     * created from a browser — so that the optimistic row and the authoritative
     * one are the same row rather than two that have to be reconciled
     * (research/data-modeling/zero-schema-conventions.md).
     *
     * `insert`, not `upsert`, and that is a security choice rather than a
     * stylistic one: `upsert` addressed by primary key would let a client send
     * another user's tag id and overwrite that tag — including its `userId` —
     * turning create into a theft. `insert` fails on a duplicate key instead.
     * Rebase does not need `upsert` here, because a rebase rolls the optimistic
     * row back before re-running, so the insert lands on an empty slot.
     */
    create: defineMutator(
      z.object({ id: z.uuid(), name: tagNameSchema() }),
      async ({ args, ctx, tx }) => {
        const session = requireSession(ctx)
        await tx.mutate.tags.insert({
          id: args.id,
          userId: session.id,
          name: args.name,
          createdAt: Date.now(),
        })
      },
    ),

    /**
     * Delete a tag, and with it every application of that tag.
     *
     * The `article_tags` rows go by `ON DELETE CASCADE` rather than by a second
     * write here — one statement, one transaction, and no window in which a
     * join row points at a tag that no longer exists.
     */
    delete: defineMutator(
      z.object({ id: z.uuid() }),
      async ({ args, ctx, tx }) => {
        const session = requireSession(ctx)
        await requireOwnedTag(tx, session, args.id)
        await tx.mutate.tags.delete({ id: args.id })
      },
    ),

    /**
     * Apply a tag to an article. Both must belong to the caller.
     *
     * **Idempotent by construction**, which the task requires twice over: a
     * reader who picks the same tag again should see nothing happen rather than
     * an error, and Zero re-runs this on every rebase while the mutation is in
     * flight. Checking for the existing row is what provides it; the database's
     * `unique (article_id, tag_id)` is the backstop underneath, for the case
     * where two clients attach the same tag at once and neither read saw the
     * other's write.
     */
    attach: defineMutator(
      z.object({ id: z.uuid(), articleId: z.uuid(), tagId: z.uuid() }),
      async ({ args, ctx, tx }) => {
        const session = requireSession(ctx)
        // Both ends, not just one: an article you own may not be tagged with
        // someone else's tag, and your tag may not be applied to their article.
        await requireOwnedArticle(tx, session, args.articleId)
        await requireOwnedTag(tx, session, args.tagId)

        const existing = await findArticleTag(tx, args.articleId, args.tagId)
        if (existing) {
          return
        }

        await tx.mutate.articleTags.insert({
          id: args.id,
          articleId: args.articleId,
          tagId: args.tagId,
          createdAt: Date.now(),
        })
      },
    ),

    /**
     * Remove a tag from an article, leaving the tag itself alone.
     *
     * Addressed by the pair rather than by the join row's id, because that is
     * what the caller knows: the card holds an article and a tag, and the row
     * joining them is an implementation detail it has no reason to track.
     * Removing a tag that is not applied is a no-op, for the same
     * run-me-twice reason `attach` is.
     */
    detach: defineMutator(
      z.object({ articleId: z.uuid(), tagId: z.uuid() }),
      async ({ args, ctx, tx }) => {
        const session = requireSession(ctx)
        await requireOwnedArticle(tx, session, args.articleId)
        await requireOwnedTag(tx, session, args.tagId)

        const existing = await findArticleTag(tx, args.articleId, args.tagId)
        if (!existing) {
          return
        }

        await tx.mutate.articleTags.delete({ id: existing.id })
      },
    ),
  },

  annotations: {
    /**
     * Store a mark the reader just made.
     *
     * **The id comes from the client and is EmbedPDF's own.** That is the same
     * property every other create here has — a client-generated primary key, so
     * the optimistic row and the authoritative one are one row — and it is
     * `insert` rather than `upsert` for the same security reason as
     * `tags.create`: an upsert addressed by primary key would let a client name
     * someone else's annotation id and overwrite that row, including its
     * `userId`. A duplicate key fails instead.
     *
     * The payload is passed through unvalidated beyond "a JSON object", because
     * its shape belongs to EmbedPDF and differs per annotation type. That is not
     * a hole: nothing on the server interprets it, it is scoped to a row this
     * user owns, and it comes back out only to the browser that wrote it. What
     * *is* checked is everything authorization depends on — the article, and the
     * owner, which is taken from the session and never from the arguments.
     */
    create: defineMutator(
      z.object({
        id: z.uuid(),
        articleId: z.uuid(),
        type: z.enum(ANNOTATION_TYPES),
        pageIndex: z.int().min(0),
        contents: z.string().max(20_000).nullable(),
        payload: annotationPayloadSchema(),
      }),
      async ({ args, ctx, tx }) => {
        const session = requireSession(ctx)
        await requireOwnedArticle(tx, session, args.articleId)

        const now = Date.now()
        await tx.mutate.annotations.insert({
          id: args.id,
          userId: session.id,
          articleId: args.articleId,
          type: args.type,
          pageIndex: args.pageIndex,
          contents: args.contents,
          payload: args.payload,
          createdAt: now,
          updatedAt: now,
        })
      },
    ),

    /**
     * Replace a mark's geometry and contents after the reader moved, resized, or
     * retyped it.
     *
     * The whole payload rather than a patch, for the reason `articles.setNotes`
     * gives: the writer holds the complete object the engine handed it, so a
     * patch protocol would be machinery for merging edits that only ever come
     * from one editor at a time. It is also what makes this safe to re-run on
     * rebase — writing the same object twice is writing it once.
     *
     * `type` is deliberately not updatable. A highlight does not become an ink
     * stroke; a request that says so is a bug in the caller, and refusing to
     * encode it keeps the column trustworthy.
     */
    update: defineMutator(
      z.object({
        id: z.uuid(),
        pageIndex: z.int().min(0),
        contents: z.string().max(20_000).nullable(),
        payload: annotationPayloadSchema(),
      }),
      async ({ args, ctx, tx }) => {
        const session = requireSession(ctx)
        await requireOwnedAnnotation(tx, session, args.id)

        await tx.mutate.annotations.update({
          id: args.id,
          pageIndex: args.pageIndex,
          contents: args.contents,
          payload: args.payload,
          updatedAt: Date.now(),
        })
      },
    ),

    /**
     * Remove a mark. Hard delete, per
     * research/data-modeling/zero-schema-conventions.md — there is no undo in
     * this reader by decision, so a tombstone would be a row kept for nothing.
     *
     * Guarded like `tags.delete`, and refusing the same way: an annotation that
     * is not there and one that is someone else's are one answer, so neither
     * confirms the other's existence.
     */
    delete: defineMutator(
      z.object({ id: z.uuid() }),
      async ({ args, ctx, tx }) => {
        const session = requireSession(ctx)
        await requireOwnedAnnotation(tx, session, args.id)
        await tx.mutate.annotations.delete({ id: args.id })
      },
    ),
  },

  articles: {
    /**
     * Set where the reader has got to.
     *
     * Mutual exclusivity needs no work here and no constraint in the database:
     * `articles.status` is a single-valued column, so setting one status is what
     * clears the previous one. That is the whole reason reading status is a
     * column rather than three seeded tag rows
     * (research/data-modeling/tags-and-reading-status.md) — the alternative
     * needed a partial unique index to buy the same property.
     *
     * `update` touches only the named column, so this cannot disturb anything
     * the extraction pipeline wrote.
     */
    setStatus: defineMutator(
      z.object({ id: z.uuid(), status: z.enum(ARTICLE_STATUSES) }),
      async ({ args, ctx, tx }) => {
        const session = requireSession(ctx)
        await requireOwnedArticle(tx, session, args.id)
        await tx.mutate.articles.update({ id: args.id, status: args.status })
      },
    ),

    /**
     * Replace an article's free-text notes — the reader's own writing about the
     * paper, distinct from the annotations anchored inside the PDF
     * (research/ui-ux/pages/lit-tracker/pages/article-detail.md).
     *
     * **The whole value, not a patch.** One textarea is bound to one column, so
     * last-write-wins is what a diff would compute anyway for a single editor,
     * and a patch protocol would be machinery bought for a case this app does
     * not have. It is also what makes this safe to re-run on rebase: writing the
     * same string twice is writing it once.
     *
     * `notesSchema` allows the empty string deliberately. Clearing the field is
     * a thing a reader does, and it must store as `''` rather than becoming
     * `null` — one absent-notes representation, so nothing downstream has to
     * decide whether the two mean different things.
     */
    setNotes: defineMutator(
      z.object({ id: z.uuid(), notes: notesSchema() }),
      async ({ args, ctx, tx }) => {
        const session = requireSession(ctx)
        await requireOwnedArticle(tx, session, args.id)
        await tx.mutate.articles.update({ id: args.id, notes: args.notes })
      },
    ),
  },
})

/**
 * A tag name as the user may submit it.
 *
 * Trimmed before validation rather than after, so that a name of nothing but
 * spaces is rejected instead of stored as an empty string — the tag entry
 * accepts free text, and "  " is a plausible thing to type by accident. The
 * upper bound is a display concern rather than a storage one: the column is
 * `text`, but a tag chip that is longer than the card carrying it is not a tag.
 */
function tagNameSchema() {
  return z.string().trim().min(1).max(64)
}

/**
 * An article's notes as the user may submit them.
 *
 * **Not trimmed, unlike a tag name.** This is prose the reader is in the middle
 * of writing: trimming would delete the newline they just pressed and move
 * their cursor, every time the debounce fired. The empty string is valid — that
 * is a cleared field, not an invalid one.
 *
 * The cap is generous because the column is `text` and this is the one place on
 * the site meant to hold paragraphs; it exists so a paste of an entire paper
 * cannot be pushed through sync as one row, not to constrain a real note.
 */
function notesSchema() {
  return z.string().max(50_000)
}

/**
 * An annotation's type-specific fields, as the reader may submit them.
 *
 * Validated as "a JSON object" and no further, on purpose. The fields differ per
 * annotation type and their shape is EmbedPDF's to define, so a schema listing
 * them here would be a second, hand-maintained copy of a library's internals —
 * wrong the first time the library adds a property, and wrong in the direction
 * that silently drops what the engine needs to redraw the mark.
 *
 * What it does insist on is that the values are **JSON** — Zod's own recursive
 * JSON type rather than `unknown`. That is not decoration: this ends up in a
 * `jsonb` column and travels through Zero, both of which can only carry JSON, so
 * a payload holding a `Date` or a function must be refused here rather than
 * losing a field somewhere downstream where nobody is looking. The reader's
 * translation layer is what strips the one such field EmbedPDF supplies (its
 * `Date` timestamps) before a payload ever reaches this.
 */
function annotationPayloadSchema() {
  return z.record(z.string(), z.json())
}

/**
 * The row joining an article to a tag, if the tag is currently applied.
 *
 * Ownership is *not* checked here — every caller has already checked both ends,
 * and re-deriving it from the join row would be a third place for the same
 * question to be answered differently. Kept private to this module so that
 * stays true.
 */
async function findArticleTag(
  tx: Transaction,
  articleId: string,
  tagId: string,
) {
  const [row] = await tx.run(
    zql.articleTags
      .where('articleId', articleId)
      .where('tagId', tagId)
      .limit(1),
  )
  return row
}
