// @generated drizzle-zero signature:sha256:447917092f1d213fc8245069452756fc148167c457ee52a7e6e92d22c781333d
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from '@rocicorp/zero'
import { createBuilder } from '@rocicorp/zero'
import type { ZeroCustomType } from 'drizzle-zero'
import type { default as zeroSchema } from '../../drizzle-zero.config'

const articleTagsTable = {
  name: 'articleTags',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    articleId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'article_id',
    },
    tagId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'tag_id',
    },
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
  },
  primaryKey: ['id'],
  serverName: 'article_tags',
} as const
const articlesTable = {
  name: 'articles',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'user_id',
    },
    title: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    authors: {
      type: 'json',
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        'articles',
        'authors'
      >,
    },
    publicationYear: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'publication_year',
    },
    venue: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    doi: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    abstract: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    notes: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    pdfObjectKey: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'pdf_object_key',
    },
    semanticScholarId: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'semantic_scholar_id',
    },
    status: {
      type: 'string',
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        'articles',
        'status'
      >,
    },
    extractionStatus: {
      type: 'string',
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        'articles',
        'extractionStatus'
      >,
      serverName: 'extraction_status',
    },
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    updatedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'updated_at',
    },
  },
  primaryKey: ['id'],
} as const
const citationEdgesTable = {
  name: 'citationEdges',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'user_id',
    },
    citingArticleId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'citing_article_id',
    },
    citedArticleId: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'cited_article_id',
    },
    title: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    authors: {
      type: 'json',
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        'citationEdges',
        'authors'
      >,
    },
    publicationYear: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'publication_year',
    },
    semanticScholarId: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'semantic_scholar_id',
    },
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    updatedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'updated_at',
    },
  },
  primaryKey: ['id'],
  serverName: 'citation_edges',
} as const
const tagsTable = {
  name: 'tags',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'user_id',
    },
    name: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
  },
  primaryKey: ['id'],
} as const
const uploadJobsTable = {
  name: 'uploadJobs',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'user_id',
    },
    filename: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    status: {
      type: 'string',
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        'uploadJobs',
        'status'
      >,
    },
    failureReason: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'failure_reason',
    },
    articleId: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'article_id',
    },
    pdfObjectKey: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'pdf_object_key',
    },
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    updatedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'updated_at',
    },
  },
  primaryKey: ['id'],
  serverName: 'upload_jobs',
} as const
const articleTagsRelationships = {
  article: [
    {
      sourceField: ['articleId'],
      destField: ['id'],
      destSchema: 'articles',
      cardinality: 'one',
    },
  ],
  tag: [
    {
      sourceField: ['tagId'],
      destField: ['id'],
      destSchema: 'tags',
      cardinality: 'one',
    },
  ],
} as const
const articlesRelationships = {
  uploadJobs: [
    {
      sourceField: ['id'],
      destField: ['articleId'],
      destSchema: 'uploadJobs',
      cardinality: 'many',
    },
  ],
  articleTags: [
    {
      sourceField: ['id'],
      destField: ['articleId'],
      destSchema: 'articleTags',
      cardinality: 'many',
    },
  ],
  references: [
    {
      sourceField: ['id'],
      destField: ['citingArticleId'],
      destSchema: 'citationEdges',
      cardinality: 'many',
    },
  ],
  citedBy: [
    {
      sourceField: ['id'],
      destField: ['citedArticleId'],
      destSchema: 'citationEdges',
      cardinality: 'many',
    },
  ],
} as const
const citationEdgesRelationships = {
  citingArticle: [
    {
      sourceField: ['citingArticleId'],
      destField: ['id'],
      destSchema: 'articles',
      cardinality: 'one',
    },
  ],
  citedArticle: [
    {
      sourceField: ['citedArticleId'],
      destField: ['id'],
      destSchema: 'articles',
      cardinality: 'one',
    },
  ],
} as const
const tagsRelationships = {
  articleTags: [
    {
      sourceField: ['id'],
      destField: ['tagId'],
      destSchema: 'articleTags',
      cardinality: 'many',
    },
  ],
} as const
const uploadJobsRelationships = {
  article: [
    {
      sourceField: ['articleId'],
      destField: ['id'],
      destSchema: 'articles',
      cardinality: 'one',
    },
  ],
} as const
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    articleTags: articleTagsTable,
    articles: articlesTable,
    citationEdges: citationEdgesTable,
    tags: tagsTable,
    uploadJobs: uploadJobsTable,
  },
  relationships: {
    articleTags: articleTagsRelationships,
    articles: articlesRelationships,
    citationEdges: citationEdgesRelationships,
    tags: tagsRelationships,
    uploadJobs: uploadJobsRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema
/**
 * Represents a row from the "articleTags" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ArticleTag = Row<(typeof schema)['tables']['articleTags']>
/**
 * Represents a row from the "articles" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Article = Row<(typeof schema)['tables']['articles']>
/**
 * Represents a row from the "citationEdges" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type CitationEdge = Row<(typeof schema)['tables']['citationEdges']>
/**
 * Represents a row from the "tags" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Tag = Row<(typeof schema)['tables']['tags']>
/**
 * Represents a row from the "uploadJobs" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type UploadJob = Row<(typeof schema)['tables']['uploadJobs']>

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema)
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql

/** Defines the default types for Zero */
declare module '@rocicorp/zero' {
  interface DefaultTypes {
    schema: Schema
  }
}
