// @generated drizzle-zero signature:sha256:18169cafb9ed51cc15100153199d8a36fea410895d8d43617c260057f7b9bb78
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from '@rocicorp/zero'
import { createBuilder } from '@rocicorp/zero'
import type { ZeroCustomType } from 'drizzle-zero'
import type { default as zeroSchema } from '../../drizzle-zero.config'

const articlesTable = {
  name: 'articles',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'user_id',
    },
    title: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    authors: {
      type: 'json',
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        'articles',
        'authors'
      >,
    },
    publicationYear: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'publication_year',
    },
    venue: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    doi: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    abstract: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    notes: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    pdfObjectKey: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'pdf_object_key',
    },
    semanticScholarId: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'semantic_scholar_id',
    },
    status: {
      type: 'string',
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        'articles',
        'status'
      >,
    },
    extractionStatus: {
      type: 'string',
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        'articles',
        'extractionStatus'
      >,
      serverName: 'extraction_status',
    },
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    updatedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'updated_at',
    },
  },
  primaryKey: ['id'],
} as const
const uploadJobsTable = {
  name: 'uploadJobs',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'user_id',
    },
    filename: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    status: {
      type: 'string',
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        'uploadJobs',
        'status'
      >,
    },
    failureReason: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'failure_reason',
    },
    articleId: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'article_id',
    },
    pdfObjectKey: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'pdf_object_key',
    },
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    updatedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'updated_at',
    },
  },
  primaryKey: ['id'],
  serverName: 'upload_jobs',
} as const
const articlesRelationships = {
  uploadJobs: [
    {
      sourceField: ['id'],
      destField: ['articleId'],
      destSchema: 'uploadJobs',
      cardinality: 'many',
    },
  ],
} as const
const uploadJobsRelationships = {
  article: [
    {
      sourceField: ['articleId'],
      destField: ['id'],
      destSchema: 'articles',
      cardinality: 'one',
    },
  ],
} as const
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    articles: articlesTable,
    uploadJobs: uploadJobsTable,
  },
  relationships: {
    articles: articlesRelationships,
    uploadJobs: uploadJobsRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema
/**
 * Represents a row from the "articles" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Article = Row<(typeof schema)['tables']['articles']>
/**
 * Represents a row from the "uploadJobs" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type UploadJob = Row<(typeof schema)['tables']['uploadJobs']>

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema)
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql

/** Defines the default types for Zero */
declare module '@rocicorp/zero' {
  interface DefaultTypes {
    schema: Schema
  }
}
