/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErrorProbeRouteImport } from './routes/error-probe'
import { Route as personalSiteRouteRouteImport } from './routes/(personal-site)/route'
import { Route as personalSiteIndexRouteImport } from './routes/(personal-site)/index'
import { Route as personalSiteProjectsRouteImport } from './routes/(personal-site)/projects'
import { Route as personalSiteBlogRouteImport } from './routes/(personal-site)/blog'
import { Route as personalSiteAboutRouteImport } from './routes/(personal-site)/about'

const ErrorProbeRoute = ErrorProbeRouteImport.update({
  id: '/error-probe',
  path: '/error-probe',
  getParentRoute: () => rootRouteImport,
} as any)
const personalSiteRouteRoute = personalSiteRouteRouteImport.update({
  id: '/(personal-site)',
  getParentRoute: () => rootRouteImport,
} as any)
const personalSiteIndexRoute = personalSiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => personalSiteRouteRoute,
} as any)
const personalSiteProjectsRoute = personalSiteProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => personalSiteRouteRoute,
} as any)
const personalSiteBlogRoute = personalSiteBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => personalSiteRouteRoute,
} as any)
const personalSiteAboutRoute = personalSiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => personalSiteRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/error-probe': typeof ErrorProbeRoute
  '/about': typeof personalSiteAboutRoute
  '/blog': typeof personalSiteBlogRoute
  '/projects': typeof personalSiteProjectsRoute
  '/': typeof personalSiteIndexRoute
}
export interface FileRoutesByTo {
  '/error-probe': typeof ErrorProbeRoute
  '/about': typeof personalSiteAboutRoute
  '/blog': typeof personalSiteBlogRoute
  '/projects': typeof personalSiteProjectsRoute
  '/': typeof personalSiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(personal-site)': typeof personalSiteRouteRouteWithChildren
  '/error-probe': typeof ErrorProbeRoute
  '/(personal-site)/about': typeof personalSiteAboutRoute
  '/(personal-site)/blog': typeof personalSiteBlogRoute
  '/(personal-site)/projects': typeof personalSiteProjectsRoute
  '/(personal-site)/': typeof personalSiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/error-probe' | '/about' | '/blog' | '/projects' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/error-probe' | '/about' | '/blog' | '/projects' | '/'
  id:
    | '__root__'
    | '/(personal-site)'
    | '/error-probe'
    | '/(personal-site)/about'
    | '/(personal-site)/blog'
    | '/(personal-site)/projects'
    | '/(personal-site)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  personalSiteRouteRoute: typeof personalSiteRouteRouteWithChildren
  ErrorProbeRoute: typeof ErrorProbeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error-probe': {
      id: '/error-probe'
      path: '/error-probe'
      fullPath: '/error-probe'
      preLoaderRoute: typeof ErrorProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(personal-site)': {
      id: '/(personal-site)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof personalSiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(personal-site)/': {
      id: '/(personal-site)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof personalSiteIndexRouteImport
      parentRoute: typeof personalSiteRouteRoute
    }
    '/(personal-site)/projects': {
      id: '/(personal-site)/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof personalSiteProjectsRouteImport
      parentRoute: typeof personalSiteRouteRoute
    }
    '/(personal-site)/blog': {
      id: '/(personal-site)/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof personalSiteBlogRouteImport
      parentRoute: typeof personalSiteRouteRoute
    }
    '/(personal-site)/about': {
      id: '/(personal-site)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof personalSiteAboutRouteImport
      parentRoute: typeof personalSiteRouteRoute
    }
  }
}

interface personalSiteRouteRouteChildren {
  personalSiteAboutRoute: typeof personalSiteAboutRoute
  personalSiteBlogRoute: typeof personalSiteBlogRoute
  personalSiteProjectsRoute: typeof personalSiteProjectsRoute
  personalSiteIndexRoute: typeof personalSiteIndexRoute
}

const personalSiteRouteRouteChildren: personalSiteRouteRouteChildren = {
  personalSiteAboutRoute: personalSiteAboutRoute,
  personalSiteBlogRoute: personalSiteBlogRoute,
  personalSiteProjectsRoute: personalSiteProjectsRoute,
  personalSiteIndexRoute: personalSiteIndexRoute,
}

const personalSiteRouteRouteWithChildren =
  personalSiteRouteRoute._addFileChildren(personalSiteRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  personalSiteRouteRoute: personalSiteRouteRouteWithChildren,
  ErrorProbeRoute: ErrorProbeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
