/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErrorProbeRouteImport } from './routes/error-probe'
import { Route as personalSiteRouteRouteImport } from './routes/(personal-site)/route'
import { Route as personalSiteProjectsRouteImport } from './routes/(personal-site)/projects'
import { Route as personalSiteAboutRouteRouteImport } from './routes/(personal-site)/about/route'
import { Route as personalSiteBlogIndexRouteImport } from './routes/(personal-site)/blog/index'
import { Route as personalSitehomeIndexRouteImport } from './routes/(personal-site)/(home)/index'
import { Route as personalSiteBlogSlugRouteImport } from './routes/(personal-site)/blog/$slug'

const ErrorProbeRoute = ErrorProbeRouteImport.update({
  id: '/error-probe',
  path: '/error-probe',
  getParentRoute: () => rootRouteImport,
} as any)
const personalSiteRouteRoute = personalSiteRouteRouteImport.update({
  id: '/(personal-site)',
  getParentRoute: () => rootRouteImport,
} as any)
const personalSiteProjectsRoute = personalSiteProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => personalSiteRouteRoute,
} as any)
const personalSiteAboutRouteRoute = personalSiteAboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => personalSiteRouteRoute,
} as any)
const personalSiteBlogIndexRoute = personalSiteBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => personalSiteRouteRoute,
} as any)
const personalSitehomeIndexRoute = personalSitehomeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => personalSiteRouteRoute,
} as any)
const personalSiteBlogSlugRoute = personalSiteBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => personalSiteRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/error-probe': typeof ErrorProbeRoute
  '/about': typeof personalSiteAboutRouteRoute
  '/projects': typeof personalSiteProjectsRoute
  '/blog/$slug': typeof personalSiteBlogSlugRoute
  '/': typeof personalSitehomeIndexRoute
  '/blog/': typeof personalSiteBlogIndexRoute
}
export interface FileRoutesByTo {
  '/error-probe': typeof ErrorProbeRoute
  '/about': typeof personalSiteAboutRouteRoute
  '/projects': typeof personalSiteProjectsRoute
  '/blog/$slug': typeof personalSiteBlogSlugRoute
  '/': typeof personalSitehomeIndexRoute
  '/blog': typeof personalSiteBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(personal-site)': typeof personalSiteRouteRouteWithChildren
  '/error-probe': typeof ErrorProbeRoute
  '/(personal-site)/about': typeof personalSiteAboutRouteRoute
  '/(personal-site)/projects': typeof personalSiteProjectsRoute
  '/(personal-site)/blog/$slug': typeof personalSiteBlogSlugRoute
  '/(personal-site)/(home)/': typeof personalSitehomeIndexRoute
  '/(personal-site)/blog/': typeof personalSiteBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/error-probe' | '/about' | '/projects' | '/blog/$slug' | '/' | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to: '/error-probe' | '/about' | '/projects' | '/blog/$slug' | '/' | '/blog'
  id:
    | '__root__'
    | '/(personal-site)'
    | '/error-probe'
    | '/(personal-site)/about'
    | '/(personal-site)/projects'
    | '/(personal-site)/blog/$slug'
    | '/(personal-site)/(home)/'
    | '/(personal-site)/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  personalSiteRouteRoute: typeof personalSiteRouteRouteWithChildren
  ErrorProbeRoute: typeof ErrorProbeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error-probe': {
      id: '/error-probe'
      path: '/error-probe'
      fullPath: '/error-probe'
      preLoaderRoute: typeof ErrorProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(personal-site)': {
      id: '/(personal-site)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof personalSiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(personal-site)/projects': {
      id: '/(personal-site)/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof personalSiteProjectsRouteImport
      parentRoute: typeof personalSiteRouteRoute
    }
    '/(personal-site)/about': {
      id: '/(personal-site)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof personalSiteAboutRouteRouteImport
      parentRoute: typeof personalSiteRouteRoute
    }
    '/(personal-site)/blog/': {
      id: '/(personal-site)/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof personalSiteBlogIndexRouteImport
      parentRoute: typeof personalSiteRouteRoute
    }
    '/(personal-site)/(home)/': {
      id: '/(personal-site)/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof personalSitehomeIndexRouteImport
      parentRoute: typeof personalSiteRouteRoute
    }
    '/(personal-site)/blog/$slug': {
      id: '/(personal-site)/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof personalSiteBlogSlugRouteImport
      parentRoute: typeof personalSiteRouteRoute
    }
  }
}

interface personalSiteRouteRouteChildren {
  personalSiteAboutRouteRoute: typeof personalSiteAboutRouteRoute
  personalSiteProjectsRoute: typeof personalSiteProjectsRoute
  personalSiteBlogSlugRoute: typeof personalSiteBlogSlugRoute
  personalSitehomeIndexRoute: typeof personalSitehomeIndexRoute
  personalSiteBlogIndexRoute: typeof personalSiteBlogIndexRoute
}

const personalSiteRouteRouteChildren: personalSiteRouteRouteChildren = {
  personalSiteAboutRouteRoute: personalSiteAboutRouteRoute,
  personalSiteProjectsRoute: personalSiteProjectsRoute,
  personalSiteBlogSlugRoute: personalSiteBlogSlugRoute,
  personalSitehomeIndexRoute: personalSitehomeIndexRoute,
  personalSiteBlogIndexRoute: personalSiteBlogIndexRoute,
}

const personalSiteRouteRouteWithChildren =
  personalSiteRouteRoute._addFileChildren(personalSiteRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  personalSiteRouteRoute: personalSiteRouteRouteWithChildren,
  ErrorProbeRoute: ErrorProbeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
