/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErrorProbeRouteImport } from './routes/error-probe'
import { Route as SignInRouteRouteImport } from './routes/sign-in/route'
import { Route as personalSiteRouteRouteImport } from './routes/(personal-site)/route'
import { Route as personalSiteProjectsRouteRouteImport } from './routes/(personal-site)/projects/route'
import { Route as personalSiteAboutRouteRouteImport } from './routes/(personal-site)/about/route'
import { Route as personalSiteBlogIndexRouteImport } from './routes/(personal-site)/blog/index'
import { Route as personalSitehomeIndexRouteImport } from './routes/(personal-site)/(home)/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as personalSiteBlogSlugRouteImport } from './routes/(personal-site)/blog/$slug'

const ErrorProbeRoute = ErrorProbeRouteImport.update({
  id: '/error-probe',
  path: '/error-probe',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRouteRoute = SignInRouteRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const personalSiteRouteRoute = personalSiteRouteRouteImport.update({
  id: '/(personal-site)',
  getParentRoute: () => rootRouteImport,
} as any)
const personalSiteProjectsRouteRoute =
  personalSiteProjectsRouteRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => personalSiteRouteRoute,
  } as any)
const personalSiteAboutRouteRoute = personalSiteAboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => personalSiteRouteRoute,
} as any)
const personalSiteBlogIndexRoute = personalSiteBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => personalSiteRouteRoute,
} as any)
const personalSitehomeIndexRoute = personalSitehomeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => personalSiteRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const personalSiteBlogSlugRoute = personalSiteBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => personalSiteRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof SignInRouteRoute
  '/error-probe': typeof ErrorProbeRoute
  '/about': typeof personalSiteAboutRouteRoute
  '/projects': typeof personalSiteProjectsRouteRoute
  '/blog/$slug': typeof personalSiteBlogSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof personalSitehomeIndexRoute
  '/blog/': typeof personalSiteBlogIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRouteRoute
  '/error-probe': typeof ErrorProbeRoute
  '/about': typeof personalSiteAboutRouteRoute
  '/projects': typeof personalSiteProjectsRouteRoute
  '/blog/$slug': typeof personalSiteBlogSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof personalSitehomeIndexRoute
  '/blog': typeof personalSiteBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(personal-site)': typeof personalSiteRouteRouteWithChildren
  '/sign-in': typeof SignInRouteRoute
  '/error-probe': typeof ErrorProbeRoute
  '/(personal-site)/about': typeof personalSiteAboutRouteRoute
  '/(personal-site)/projects': typeof personalSiteProjectsRouteRoute
  '/(personal-site)/blog/$slug': typeof personalSiteBlogSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(personal-site)/(home)/': typeof personalSitehomeIndexRoute
  '/(personal-site)/blog/': typeof personalSiteBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/error-probe'
    | '/about'
    | '/projects'
    | '/blog/$slug'
    | '/api/auth/$'
    | '/'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/error-probe'
    | '/about'
    | '/projects'
    | '/blog/$slug'
    | '/api/auth/$'
    | '/'
    | '/blog'
  id:
    | '__root__'
    | '/(personal-site)'
    | '/sign-in'
    | '/error-probe'
    | '/(personal-site)/about'
    | '/(personal-site)/projects'
    | '/(personal-site)/blog/$slug'
    | '/api/auth/$'
    | '/(personal-site)/(home)/'
    | '/(personal-site)/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  personalSiteRouteRoute: typeof personalSiteRouteRouteWithChildren
  SignInRouteRoute: typeof SignInRouteRoute
  ErrorProbeRoute: typeof ErrorProbeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error-probe': {
      id: '/error-probe'
      path: '/error-probe'
      fullPath: '/error-probe'
      preLoaderRoute: typeof ErrorProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(personal-site)': {
      id: '/(personal-site)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof personalSiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(personal-site)/projects': {
      id: '/(personal-site)/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof personalSiteProjectsRouteRouteImport
      parentRoute: typeof personalSiteRouteRoute
    }
    '/(personal-site)/about': {
      id: '/(personal-site)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof personalSiteAboutRouteRouteImport
      parentRoute: typeof personalSiteRouteRoute
    }
    '/(personal-site)/blog/': {
      id: '/(personal-site)/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof personalSiteBlogIndexRouteImport
      parentRoute: typeof personalSiteRouteRoute
    }
    '/(personal-site)/(home)/': {
      id: '/(personal-site)/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof personalSitehomeIndexRouteImport
      parentRoute: typeof personalSiteRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(personal-site)/blog/$slug': {
      id: '/(personal-site)/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof personalSiteBlogSlugRouteImport
      parentRoute: typeof personalSiteRouteRoute
    }
  }
}

interface personalSiteRouteRouteChildren {
  personalSiteAboutRouteRoute: typeof personalSiteAboutRouteRoute
  personalSiteProjectsRouteRoute: typeof personalSiteProjectsRouteRoute
  personalSiteBlogSlugRoute: typeof personalSiteBlogSlugRoute
  personalSitehomeIndexRoute: typeof personalSitehomeIndexRoute
  personalSiteBlogIndexRoute: typeof personalSiteBlogIndexRoute
}

const personalSiteRouteRouteChildren: personalSiteRouteRouteChildren = {
  personalSiteAboutRouteRoute: personalSiteAboutRouteRoute,
  personalSiteProjectsRouteRoute: personalSiteProjectsRouteRoute,
  personalSiteBlogSlugRoute: personalSiteBlogSlugRoute,
  personalSitehomeIndexRoute: personalSitehomeIndexRoute,
  personalSiteBlogIndexRoute: personalSiteBlogIndexRoute,
}

const personalSiteRouteRouteWithChildren =
  personalSiteRouteRoute._addFileChildren(personalSiteRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  personalSiteRouteRoute: personalSiteRouteRouteWithChildren,
  SignInRouteRoute: SignInRouteRoute,
  ErrorProbeRoute: ErrorProbeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
